# Generated by Django 5.1.7 on 2025-04-06 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anime_title', models.CharField(max_length=255)),
                ('episode_number', models.PositiveIntegerField()),
                ('cover_image_url', models.URLField(blank=True, help_text='URL to the anime cover image', max_length=500, null=True)),
                ('content_type', models.CharField(blank=True, help_text='Type of content: TV, Movie, OVA, Special, etc.', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'anime_title', 'episode_number')},
            },
        ),
    ]
