# Generated by Django 5.1.7 on 2025-04-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_watchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchhistory',
            name='watch_url',
            field=models.URLField(blank=True, help_text='URL to the episode being watched', max_length=500, null=True),
        ),
    ]
