# Generated by Django 5.1.7 on 2025-04-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_watchhistory_watch_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='watch_histories', to='api.genre'),
        ),
    ]
