# Generated by Django 5.1.7 on 2025-04-07 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_genre_watchhistory_genres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manga_title', models.CharField(max_length=255)),
                ('chapter_name', models.CharField(max_length=255)),
                ('cover_image_url', models.URLField(blank=True, help_text='URL to the manga cover image', max_length=500, null=True)),
                ('read_url', models.URLField(blank=True, help_text='URL to the manga chapter being read', max_length=500, null=True)),
                ('total_pages', models.PositiveIntegerField(blank=True, help_text='Total number of pages in the chapter', null=True)),
                ('last_read_page', models.PositiveIntegerField(blank=True, help_text='Last page the user read', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='read_histories', to='api.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'manga_title', 'chapter_name')},
            },
        ),
    ]
